package com.app.entity;
// Generated 2013-07-01 23:02:39 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MAttachment generated by hbm2java
 */
public class MAttachment  implements java.io.Serializable {


     private int id;
     private String chName;
     private byte[] chBinaryvalue;
     private Date dtCreatedate;

    public MAttachment() {
    }

	
    public MAttachment(int id) {
        this.id = id;
    }
    public MAttachment(int id, String chName, byte[] chBinaryvalue, Date dtCreatedate) {
       this.id = id;
       this.chName = chName;
       this.chBinaryvalue = chBinaryvalue;
       this.dtCreatedate = dtCreatedate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getChName() {
        return this.chName;
    }
    
    public void setChName(String chName) {
        this.chName = chName;
    }
    public byte[] getChBinaryvalue() {
        return this.chBinaryvalue;
    }
    
    public void setChBinaryvalue(byte[] chBinaryvalue) {
        this.chBinaryvalue = chBinaryvalue;
    }
    public Date getDtCreatedate() {
        return this.dtCreatedate;
    }
    
    public void setDtCreatedate(Date dtCreatedate) {
        this.dtCreatedate = dtCreatedate;
    }
}


