package com.app.entity;
// Generated 2013-07-03 23:10:05 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MDicionary generated by hbm2java
 */
public class MDicionary  implements java.io.Serializable {


     private int id;
     private String chValue;
     private String chType;
     private Date dtCreatedate;
     private String chItem1;

    public MDicionary() {
    }

	
    public MDicionary(int id) {
        this.id = id;
    }
    public MDicionary(int id, String chValue, String chType, Date dtCreatedate, String chItem1) {
       this.id = id;
       this.chValue = chValue;
       this.chType = chType;
       this.dtCreatedate = dtCreatedate;
       this.chItem1 = chItem1;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getChValue() {
        return this.chValue;
    }
    
    public void setChValue(String chValue) {
        this.chValue = chValue;
    }
    public String getChType() {
        return this.chType;
    }
    
    public void setChType(String chType) {
        this.chType = chType;
    }
    public Date getDtCreatedate() {
        return this.dtCreatedate;
    }
    
    public void setDtCreatedate(Date dtCreatedate) {
        this.dtCreatedate = dtCreatedate;
    }
    public String getChItem1() {
        return this.chItem1;
    }
    
    public void setChItem1(String chItem1) {
        this.chItem1 = chItem1;
    }
}


