package com.app.entity;
// Generated 2013-07-01 23:02:39 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MUser generated by hbm2java
 */
public class MUser  implements java.io.Serializable {


     private int id;
     private String chName;
     private String chLastname;
     private String chLogin;
     private String chPassword;
     private String chEmail;
     private Date dtInsertdate;

    public MUser() {
    }

	
    public MUser(int id) {
        this.id = id;
    }
    public MUser(int id, String chName, String chLastname, String chLogin, String chPassword, String chEmail, Date dtInsertdate) {
       this.id = id;
       this.chName = chName;
       this.chLastname = chLastname;
       this.chLogin = chLogin;
       this.chPassword = chPassword;
       this.chEmail = chEmail;
       this.dtInsertdate = dtInsertdate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getChName() {
        return this.chName;
    }
    
    public void setChName(String chName) {
        this.chName = chName;
    }
    public String getChLastname() {
        return this.chLastname;
    }
    
    public void setChLastname(String chLastname) {
        this.chLastname = chLastname;
    }
    public String getChLogin() {
        return this.chLogin;
    }
    
    public void setChLogin(String chLogin) {
        this.chLogin = chLogin;
    }
    public String getChPassword() {
        return this.chPassword;
    }
    
    public void setChPassword(String chPassword) {
        this.chPassword = chPassword;
    }
    public String getChEmail() {
        return this.chEmail;
    }
    
    public void setChEmail(String chEmail) {
        this.chEmail = chEmail;
    }
    public Date getDtInsertdate() {
        return this.dtInsertdate;
    }
    
    public void setDtInsertdate(Date dtInsertdate) {
        this.dtInsertdate = dtInsertdate;
    }
    
}


